version: "3.1"
services:
    mysql:
        image: mysql:5.7
        volumes:
            - ./mysql:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=easyappointments
        ports:
            - "8001:3306"
    server:
        build: ./server
        image: easyappointments-server:v1
        container_name: easyappointments-server
        ports:
            - "8000:80"
        volumes:
            - ./config.php:/var/www/html/config.php

    adminer:
        image: adminer:latest
        ports:
            - '8002:8080'
